language: scala

jdk:
    - oraclejdk8

version:
    - 2.12.1

before_script:
    - psql -c 'CREATE USER wow;'  -U postgres
    - psql -c 'CREATE DATABASE wow;' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE wow TO wow;' -U postgres

script: cd wow && sbt test

notifications:
    email: false

# For caching
# Use container-based infrastructure
sudo: false
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
before_cache:
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
    - find $HOME/.sbt -name "*.lock" -delete
